FROM python:3.9

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt
COPY ./requirements.txt /app/requirements_dev.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements_dev.txt

COPY ./sent /app/sent

CMD ["uvicorn", "sent.app:app", "--host", "0.0.0.0", "--port", "80"]
