version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 8080:80
    volumes:
      - ./sent:/app/sent
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - 3000:3000
    volumes:
      - ./sent_app/src:/app/src
